joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# arm_controller:
#   type: position_controllers/JointTrajectoryController
#   joints:
#     # - J_1
#     # - J_2
#     # - J_4
#     # - J_6
#     # - J_7
#     # - J_10
#     # - J_12
#     # - J_14
#     # - J_15
#     # - J_16
  
joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: J_1
  pid: {p: 1.0, i: 1.0, d: 1.0}
  
joint2_position_controller:
  type: effort_controllers/JointPositionController
  joint: J_2
  pid: {p: 1.0, i: 1.0, d: 1.0}  
    
joint4_position_controller:
  type: effort_controllers/JointPositionController
  joint: J_4
  pid: {p: 1.0, i: 1.0, d: 1.0}
  
joint6_position_controller:
  type: effort_controllers/JointPositionController
  joint: J_6
  pid: {p: 1.0, i: 1.0, d: 1.0} 

joint7_position_controller:
  type: effort_controllers/JointPositionController
  joint: J_7
  pid: {p: 1.0, i: 1.0, d: 1.0}
  
joint10_position_controller:
  type: effort_controllers/JointPositionController
  joint: J_10
  pid: {p: 1.0, i: 1.0, d: 1.0}  
    
joint12_position_controller:
  type: effort_controllers/JointPositionController
  joint: J_12
  pid: {p: 1.0, i: 1.0, d: 1.0}
  
joint14_position_controller:
  type: effort_controllers/JointPositionController
  joint: J_14
  pid: {p: 1.0, i: 1.0, d: 1.0}

joint15_position_controller:
  type: effort_controllers/JointPositionController
  joint: J_15
  pid: {p: 1.0, i: 1.0, d: 1.0}
  
joint16_position_controller:
  type: effort_controllers/JointPositionController
  joint: J_16
  pid: {p: 1.0, i: 1.0, d: 0.01} 
